### ISSUE TITLE
Day 4 Discussion: "how did they do that"

### ISSUE THREAD

**Issue by evanwill** [PalouseDH/symposium#6]
@Archaeo-Programmer @RenaeCamp @zturpin @sarahmnelson79 @elle4 
To broaden our discussion and think about the wider scope of digital scholarship, I would like everyone to share a DH project of interest on Thursday morning. It could be related to your projects or pitches, or just interesting for the pedagogy, academic research, or outreach potential. 

Each of us will describe the basics about our project to the group, and together we will "deconstruct" it--asking "how did they do that"--exploring the source data, people, tools, and outputs. 

See Miriam Posner's blog post [How did they make that?](http://miriamposner.com/blog/how-did-they-make-that/) or [Editorial Sustainability and Open Peer Review at Programming Historian](http://dhcommons.org/journal/issue-1/editorial-sustainability-and-open-peer-review-programming-historian) for a basic idea.

Please put a link to the project in this issue if possible so we can find it.

**Comment by evanwill** [comment]
I am going to do Ted Underwood, [paceofchange](https://github.com/tedunderwood/paceofchange) (2015), ["How Quickly Do Literary Standards Change?"](https://figshare.com/articles/How_Quickly_Do_Literary_Standards_Change_/1418394). 

so don't try to steal my idea :wink: !

**Comment by evanwill** [comment]
**Note:** this is not supposed to a big home work assignment... just find a project you are interested in (you don't need to research it), we will do the exploring and deconstructing discussion together!

**Comment by zturpin** [comment]
So many! 

I can't pick just one; I'll just drop in three DH projects here and think about them tonight:

- First, the [Open Syllabus Explorer](http://explorer.opensyllabusproject.org/), a digital map / analysis of 1,000,000 US syllabi.

- Then there's Ben Schmidt's [Gendered Language in Teacher Reviews](http://benschmidt.org/profGender/), an interactive chart that lets you explore the words used to describe male and female teachers in about 14 million reviews from RateMyProfessor.com.

- And finally, the one and only [Walt Whitman Archive](https://whitmanarchive.org/), a virtual archive of all works written by Whitman, plus manuscripts, notebooks, scribal documents, correspondence, pictures, phonograph recordings, scholarship, commentary, archival catalogs, etc.

**Comment by sarahmnelson79** [comment]
Here's one that I was just pointing out to Zach and Ray:


http://profils-14-18.tv5monde.com/#Introduction

[Profils 14-18](http://profils-14-18.tv5monde.com/#Introduction)

profils-14-18.tv5monde.com
Rencontres avec les derniers témoins de la Grande Guerre. Des témoignages vidéos inédits de combattants de toutes nationalités, servis par un travail photographique d’auteur.

Thanks, Evan!

Sarah


Dr. Sarah Nelson
Associate Professor of French
Modern Languages & Cultures
University of Idaho
875 Perimeter Dr. MS 3174
Moscow, ID 83844-3174
USA

snelson@uidaho.edu
tel.: 1-208-885-7756
FAX: 1-208-885-5221
________________________________

**Comment by elle4** [comment]
This project is over 10 years old, so it is likely quite outdated, but I'd definitely be interested in talking about how you'd go about creating something like this with contemporary tools: [Slavery's Ephemera: The Contemporary Life of the Antebellum Plantation](http://vectors.usc.edu/projects/index.php?project=56).

**Comment by RenaeCamp** [comment]
I'd like to take a look at the [DAACS](https://www.daacs.org/).  This is a project that is an incredible source of data, but that could probably do much more on the visualization/interpretation side of things.

**Comment by Archaeo-Programmer** [comment]
I'm a little late, but [OpenContext](https://opencontext.org) is really cool as it allows for digital archiving. One project that has been of particular interest to me is called [Digital Index of North American Archaeology](http://ux.opencontext.org/archaeology-site-data/), where they are hosting state archaeological site files. You can also view the archaeological site data on the OpenContext [map](https://opencontext.org/subjects-search/?proj=52-digital-index-of-north-american-archaeology-dinaa&prop=oc-gen-cat-loc-or-context---oc-gen-cat-site#3/38.11/-110.52/11/circle/Google-Satellite).

**Comment by zturpin** [comment]
PS—For a huge online gateway to tools used for both simple and sophisticated text analysis and retrieval, check out U Alberta's [TAPoR](http://tapor.ca/home).

**Comment by Archaeo-Programmer** [comment]
Also, for the Çatalhöyük archaeological site in Turkey, they have really tried to provide excavation and information about the site through their [website](http://www.catalhoyuk.com/), which has images, illustrations, and other data. They are also working on a [living archive](http://catalhoyuk.stanford.edu/), to allow for SPARQL queries and there is an API.

**Comment by ekansa** [comment]
@Archaeo-Programmer let me know if I can help! API documentation is here: https://opencontext.org/about/services

**Comment by Archaeo-Programmer** [comment]
@ekansa Great, thanks very much! We have been exploring some different digital scholarship projects this week.
