### ISSUE TITLE
More resources

### ISSUE THREAD

**Issue by zturpin** [PalouseDH/symposium#7]
Here's that article I just mentioned: Stephen Ramsay's "[The Hermeneutics of Screwing Around; or What You Do with a Million Books](https://libraries.uh.edu/wp-content/uploads/Ramsay-The-Hermeneutics-of-Screwing-Around.pdf)" (pdf link).

I don't exaggerate when I say it made me the digital scholar I am. 

For a little taste, its central anecdote on screwing around is about how [Fank Zappa](https://en.wikipedia.org/wiki/Frank_Zappa)'s life was changed when he discovered the early electronic composer [Edgard Varese](https://en.wikipedia.org/wiki/Edgard_Var%C3%A8se) by stumbling across an article in, of all things, _LOOK_ magazine....

**Comment by evanwill** [comment]
Ian Milligan, ["Illusionary Order: Online Databases, Optical Character Recognition, and Canadian History, 1997–2010"](https://muse.jhu.edu/article/527016)

**Comment by evanwill** [comment]
[Native Land](https://native-land.ca/)

p.s. read their recent message [road map](https://native-land.ca/native-land-roadmap/), very interesting questions about sustainability and reliability when a project suddenly becomes popular

**Comment by evanwill** [comment]
[Joods Monument](https://www.joodsmonument.nl/)

**Comment by Archaeo-Programmer** [comment]
[Netherlands monument website](https://www.joodsmonument.nl/) used in @zturpin and Ray's presentation.

**Comment by evanwill** [comment]
Ryan Cordell, [A DH Dossier](http://ryancordell.org/personal/dh-dossier), info on tenure process..
