### ISSUE TITLE
link to presentation slides

### ISSUE THREAD

**Issue by evanwill** [PalouseDH/symposium#8]
@Archaeo-Programmer @RenaeCamp @zturpin @sarahmnelson79 @elle4 would you be willing to share links to your pitch presentations? 
thanks!

**Comment by Archaeo-Programmer** [comment]
Here is the link to Team Kamiak's (@sarahmnelson79 and @Archaeo-Programmer) presentation for [PalouseANTH](https://docs.google.com/presentation/d/1mLWw02p7jZdwVBecYO5uoc5lmVST9BMTQlLNV2F82s8/edit?usp=sharing).

**Comment by zturpin** [comment]
Here's the link to Team Steptoe's (@zturpin's and @sunfire60's) presentation on [< meta > memorials](https://docs.google.com/presentation/d/1cS7g2r0IObzYa7-TQVXsjFWsuk-htuqNONnD2Y6Crp8/edit?usp=sharing).

**Comment by RenaeCamp** [comment]
Team Tomer's (@renaecamp and @elle4) digital teaching trunks presentation is available [here](https://vandalsuidaho-my.sharepoint.com/:p:/r/personal/camp9574_vandals_uidaho_edu/Documents/Chinese%20Women%20in%20Idaho%20Teaching%20Trunk.pptx?d=w60f405894096437cb34b5eb87635b895&csf=1&e=3OY7Pg).

**Comment by evanwill** [comment]
added to day 5 outline (with commit 619c730d15b36d07b72b29712abe1eda2f9b4ce1)

**Comment by sunfire60** [comment]
Hi Everyone,
  Not quite on task but here is the photo from our celebration lunch at Paradise Creek.  I hope to keep in touch with you all and see how you progress on your projects.  It was a pleasure!
![palouse dh symposium 5-18-18](https://user-images.githubusercontent.com/39203816/40263350-e9c66a26-5ac5-11e8-9b23-31fa1d9a1e47.jpg)
